Pastebin/Pastebin/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.urls as file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls', namespace='main_page'), name='Home'),
    path('accounts/', include('users.urls', namespace='users'), name='accounts'),
]

Pastebin/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.personal_account, name='default'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('personal_account/', views.personal_account, name='personal_account'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

Pastebin/users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_verified = models.BooleanField(default=False)
    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

Pastebin/users/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm
from django import forms
from .models import User


class UserLoginForm(forms.ModelForm):
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('email', 'password')


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}), label='Email')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirm password')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), initial=None, required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), initial=None, required=False)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'password1', 'password2', 'first_name', 'last_name')


class UserChangeDetailsForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}), required=False, initial=None)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False, initial=None)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False, initial=None)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), required=False,
                               initial=None)


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", 'class': 'form-control'}),
    )


class SetNewPassword(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label="New password confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

Pastebin/users/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy

from .forms import UserLoginForm, UserRegistrationForm, UserChangeDetailsForm, UserPasswordResetForm, SetNewPassword
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import User


def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password, backend='users.authenticate.EmailBackend')
        if user is not None:
            login(request, user, backend='users.authenticate.EmailBackend')
            return redirect('users:personal_account')
        else:
            messages.error(request, 'Incorrect email or password')
            return redirect('users:login')
    else:
        form = UserLoginForm()
        return render(request, 'users/registration/login.html', {'form': form})


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(email=email, password=password, backend='users.authenticate.EmailBackend')
            login(request, user, backend='users.authenticate.EmailBackend')
            messages.success(request, 'Successful registration')
            text_message = "Для подтверждения почты необходимо перейти по ссылке ниже."
            send_mail('Subject', text_message, 'Django-pastebin@yandex.ru', (email,), fail_silently=False)
            return redirect(reverse('users:personal_account'))
        else:
            return render(request, 'users/registration/registration.html', {'form': form})
    form = UserRegistrationForm()
    return render(request, 'users/registration/registration.html', {'form': form})


def personal_account(request):
    if request.user.is_authenticated:
        return render(request, 'users/PersonalAccount/PersonalAccountIn.html')
    else:
        return render(request, 'users/PersonalAccount/PersonalAccount.html')


def logout_user(request):
    logout(request)
    return render(request, 'users/registration/logout.html')


def edit_profile(request):
    if request.method == "POST":
        form = UserChangeDetailsForm(request.POST)
        if form.is_valid():
            user = User.objects.get(email=request.user.email)
            if form.cleaned_data['first_name']:
                user.first_name = form.cleaned_data['first_name']
            if form.cleaned_data['last_name']:
                user.last_name = form.cleaned_data['last_name']
            if form.cleaned_data['email']:
                if user.is_verified:
                    user.email = form.cleaned_data['email']
                else:
                    messages.add_message(request, messages.ERROR,
                                         'It is not possible to update the email because your last email is not verified')
            user.save()
            return redirect('users:personal_account')
        else:
            return render(request, 'users/PersonalAccount/editProfile.html', context={'form': form})
    else:
        form = UserChangeDetailsForm()
        context = {'form': form}
        return render(request, 'users/PersonalAccount/editProfile.html', context={'form': form})


class PasswordReset(PasswordResetView):
    template_name = 'users/registration/password_reset_form.html'
    form_class = UserPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/registration/password_reset_email.html'


class PasswordResetDone(PasswordResetDoneView):
    template_name = 'users/registration/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    form_class = SetNewPassword
    success_url = reverse_lazy('users:password_reset_complete')
    template_name = 'users/registration/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'users/registration/password_reset_complete.html'

Pastebin/users/templates/users/PersonalAccount/PersonalAccount.html
{% extends 'Base.html' %}
{% block header %}
<p>Личный кабинет</p>
{% endblock header %}


{% block content %}
<div class="container-fluid">
    <div class="row text-center">
        <h3>You are not logged in</h3>
    </div>
    <div class="row">
        <h4>To access your personal account and application services, you need to log in or register</h4>
    </div>
    <br>
    <div class="row">
        <div class="col-6 text-end">
            <a class="btn btn-outline-light" href="{% url 'users:registration'%}">Register</a>
        </div>
        <div class="col-6 text-start">
            <a class="btn btn-outline-light" href="{% url 'users:login'%}">Login</a>
        </div>
    </div>
    <br>
</div>
{% endblock content %}

{% block button_header %}
<div class="col-10 text-end">
    <a href="{% url 'main_page:Home' %}" class="btn btn-outline-light">Main page</a>
</div>
{% endblock button_header %}

Pastebin/users/templates/users/PersonalAccount/PersonalAccountIn.html
{% extends 'Base.html' %}


{% block header %}
<p>Account</p>
{% endblock header %}


{% block content %}
{% if user.first_name %}
<h3>Welcome, {{ user.first_name }}!</h3>
{% else %}
<h3>Welcome!</h3>
{% endif %}
{% endblock content %}


{% block button_header %}
<div class="col-4 text-end">
    <a href="{% url 'main_page:Home' %}" class="btn btn-outline-light">Main page</a>
</div>
<div class="col-3 text-center">
    <a href="{% url 'users:logout' %}" class="btn btn-outline-light">Log out</a>
</div>
<div class="col-3 text-start">
    <a href="{% url 'users:edit_profile' %}" class="btn btn-outline-light">Edit</a>
</div>
{% endblock button_header %}

Pastebin/users/templates/users/PersonalAccount/change_details.html
{% extends 'Base.html' %}

{% block content %}



{% endblock content %}

Pastebin/users/templates/users/PersonalAccount/editProfile.html
{% extends 'Base.html' %}


{% block header %}
<p>Edit account</p>
{% endblock header %}


{% block content %}
<form method="POST" action="{% url 'users:edit_profile' %}">
    {% csrf_token %}
    {% for i in form %}
    <div class="form-group row">
        <div class="col-2"></div>
        <label class="col-3 text-end col-form-label">{{ i.label }}</label>
        <div class="col-2">
            {{ i }}
        </div>
    </div>
    <br>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}


{% block button_header %}
<div class="col-6 text-end">
    <a href="{% url 'main_page:Home' %}" class="btn btn-outline-light">Main page</a>
</div>
<div class="col-6 text-start">
    <a class="btn btn-outline-light" type="button" href="{% url 'users:personal_account' %}">Account</a>
</div>
{% endblock button_header %}