Pastebin/MainApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main_page'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='Home'),
    path('accounts/', include('users.urls'), name='accounts'),

]

Pastebin/Pastebin/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.urls as file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls', namespace='main_page'), name='Home'),
    path('accounts/', include('users.urls', namespace='users'), name='accounts'),
]

Pastebin/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.personal_account, name='default'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('personal_account/', views.personal_account, name='personal_account'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

Pastebin/MainApp/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=15, verbose_name='Имя', help_text='Не более 15 символов')
    surname = models.CharField(max_length=15, verbose_name='Фамилия', help_text='Не более 15 символов')
    email = models.EmailField(null=True, blank=True)

Pastebin/MainApp/forms.py
from django import forms
from .models import User


class UserData(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'surname', 'email']

    name = forms.CharField(max_length=20)
    surname = forms.CharField(max_length=30)
    email = forms.EmailField()


class TextForm(forms.Form):
    paste = forms.CharField(widget=forms.Textarea(attrs={'row': 10, 'class': "form-control fixed-textarea"}))

    class Meta:
        fields = ['paste']

Pastebin/MainApp/views.py
from django.shortcuts import render
from .forms import TextForm
from .s3 import client
import asyncio


# Create your views here.
def save_text(request):
    with open('file1', 'w') as f:
        f.writelines(request.POST['paste'])
    asyncio.run(client.upload_file('file1'))


def home(request):
    if request.method == 'POST':
        save_text(request)
    text_description = 'Веб-приложение, которое позволяет загружать отрывки текста, обычно фрагменты исходного кода, для возможности просмотра окружающими. Такой сервис очень популярен среди пользователей IRC-сетей, где вставка больших фрагментов текста на каналы считается плохим тоном. Сервис также часто используется пользователями IM. В интернете существует множество pastebin веб-приложений, большинство из которых предоставляет подсветку синтаксиса различных языков программирования и специальной разметки.'
    text_welcome = 'Добро пожаловать на сайт Pastebin!'
    context = {
        'text_description': text_description,
        'text_welcome': text_welcome,
        'user': request.user,
        'form': TextForm()
    }
    return render(request, 'MainApp/MainPage.html', context=context)

Pastebin/MainApp/templates/MainApp/MainPage.html
{% extends 'Base.html' %}


{% block header %}
<p>Write your text and send it to anyone in just a couple of clicks!</p>
{% endblock %}


{% block stl %}
.fixed-textarea {
            width: 600px;
            height: 200px;
            resize: none;
        }
.mt-14 {
        margin-top: 14rem;
    }

{% endblock stl %}


{% block content %}
<form method="post" action="{% url 'main_page:Home' %}">
    {% csrf_token %}
    {% for i in form %}
    <div class="form-group">
        <div class="row my-3 mx-3">
        <div class="col text-start"><label>New paste</label></div>
            <div class="w-100"></div>
            <div class="col">{{ i }}</div>
        </div>
        <div class="row">
            <div class="col-3 text-start my-3 mx-5">
                <button type="submit" class="btn btn-primary">Create new paste</button>
            </div>
        </div>
    </div>
    {% endfor %}
</form>
{% endblock content %}


{% block button_header %}
    {% if user.is_authenticated %}
        <div class="col-10 text-end">
            <a class="btn btn-outline-light" type="button" href="{% url 'users:personal_account' %}">Account</a>
        </div>
    {% else %}
        <div class="col-10 text-end">
            <a class="btn btn-outline-light" type="button" href="{% url 'users:personal_account' %}">Log in</a>
        </div>
    {% endif %}
{% endblock button_header %}